name: Build Plugin RBZ

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version (e.g., 3.2.1)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    
    - name: Install dependencies
      run: |
        gem install rubyzip
    
    - name: Build RBZ
      run: |
        ruby build_rbz.rb
    
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event.inputs.version }}" != "" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        else
          echo "version=dev-$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: proGran3-plugin-${{ steps.version.outputs.version }}
        path: dist/*.rbz
        retention-days: 90
    
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.rbz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

